# MoveGripperToPoint takes in the scaled (u,v) coordinates of a click on the Wide-Angle camera.
# It then move the robot to the selected location, giving feedback on the way.

# These should be in the range [0.0, 1.0]
float64 scaled_u
float64 scaled_v

---
# Result

uint8 STATUS_SUCCESS=0
uint8 STATUS_FAILURE=1
uint8 STATUS_CANCELLED = 2
uint8 STATUS_TIMEOUT = 3
uint8 STATUS_GOAL_NOT_REACHABLE = 4
uint8 STATUS_DEPROJECTION_FAILURE = 5
uint8 STATUS_STRETCH_DRIVER_FAILURE = 6
uint8 STATUS_JOINTS_IN_COLLISION = 7

uint8 status
---
# Feedback
float32 new_scaled_u
float32 new_scaled_v
builtin_interfaces/Duration elapsed_time